### ISSUE TITLE
Validate all configuration in MusicBox curriculum examples

### ISSUE THREAD

**Issue by boulderdaze** [NCAR/music-box#161]
**Acceptance Criteria**
- Be able to run every configuration in [the MusicBox curriculum examples](https://github.com/NCAR/musicbox_curriculum_exercises)

**Ideas**
- Check all the configurations are valid
- All of them need to be runnable

**Comment by carl-drews** [comment]
I switched to the new 2FA authentication using the Duo Mobile app (green in Google Play store).

**Comment by carl-drews** [comment]
Looks like I need to install libcudart on modeling2:

(musicbox) modeling2:/home/drews/MusicBox/music-box-161-curriculum-examples/src/acom_music_box> ./goMusicBox
Traceback (most recent call last):
  File "/home/drews/.conda/envs/musicbox/bin/music_box", line 5, in <module>
    from acom_music_box.main import main
  File "/home/drews/MusicBox/music-box-161-curriculum-examples/src/acom_music_box/__init__.py", line 14, in <module>
    from .music_box import MusicBox
  File "/home/drews/MusicBox/music-box-161-curriculum-examples/src/acom_music_box/music_box.py", line 1, in <module>
    import musica
  File "/home/drews/.conda/envs/musicbox/lib/python3.12/site-packages/musica/__init__.py", line 1, in <module>
    from _musica import *
**ImportError: libcudart-b5a066d7.so.12.2.140**: cannot open shared object file: No such file or directory
(musicbox) modeling2:/home/drews/MusicBox/music-box-161-curriculum-examples/src/acom_music_box>

**Comment by K20shores** [comment]
@carl-drews Ah, that's only for newer versionso of musica. I'm trying to make sure we can install musica without needing cuda support. Maybe try to target music box version 2.7.0 for now. I have a bad wheel file that 2.8.0 targets and I'm in the process of trying to fix it

**Comment by carl-drews** [comment]
At @K20shores suggestion on Slack I changed my goBuild helper script to:
```
#pip install -e .[dev]
pip install acom_music_box==2.7.0
```

Success! No CUDA needed.

**Comment by carl-drews** [comment]
The Pull Request is Approved and Merged:
https://github.com/NCAR/musicbox_curriculum_exercises/pull/5
