### ISSUE TITLE
Last molecular concentration plot missing.

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#56]
The O3 plot is broken. conc.O3 seems to exist in the csv file, but it isn't plotted
```
2021-01-07 17:35:02,534 - Internal Server Error: /plots/get
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/music-box-interactive/interactive/plots/views.py", line 27, in get
    buffer = output_plot(str(props))
  File "/music-box-interactive/interactive/plots/plot_setup.py", line 90, in output_plot
    subset = csv[['time', ' ' + str(prop)]]
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/indexing.py", line 1265, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/indexing.py", line 1315, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "[' CONC.O3'] not in index"
[07/Jan/2021 17:35:02] "GET /plots/get?type=CONC.O3 HTTP/1.1" 500 77017
[07/Jan/2021 17:35:52] "GET /model/download HTTP/1.1" 200 53895
```

**Comment by AndrewJConley** [comment]
The previous issue was fixed, but the plots page seems to be broken now.  Is it perhaps due to the footer?
- there is not scrolling through plots
- When I unselect plots, they don't always go away.

**Comment by mattldawson** [comment]
The list of species on the right and the plots on the left scroll independently now. Is the mouse directly over the plots when you try to scroll?

**Comment by AndrewJConley** [comment]
It was something on the browser side...  I cleared the browser cache and the problem went away.
